name: Android CI


on:
  push:
    branches: [ main ]

jobs:
  build:

    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    #if: "!startsWith(github.event.head_commit.message, 'WID')"
    #if: "! contains(github.event.head_commit.message, 'gitaction')"
    #if: "contains(github.event.head_commit.message, '[build]')"
    # 如果提交WIP 就进行编译
    if: "!startsWith(github.event.head_commit.message, 'WIP')"


    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: Gradle build
      shell: bash
      continue-on-error: true
      run: |
        chmod -R 777 *
        git config core.filemode false
        ./gradlew build

  google-java-format:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    #if: "!startsWith(github.event.head_commit.message, 'WID')"
    #if: "! contains(github.event.head_commit.message, 'gitaction')"
    #if: "contains(github.event.head_commit.message, '[build]')"
    # 如果提交WIP 就进行编译
    if: "!startsWith(github.event.head_commit.message, 'WIP')"

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: google-java-format
        shell: bash
        continue-on-error: true
        run: |
          git checkout dev
          bash syncSubmodule.sh
          chmod -R 777 *
          git config core.filemode false
          echo "------------------------------------java version------------------------------------"
          java -version>format.txt
          echo "------------------------------------javac version------------------------------------"
          javac -version>>format.txt
          wget https://repo1.maven.org/maven2/com/google/googlejavaformat/google-java-format/1.12.0/google-java-format-1.12.0-all-deps.jar
          if [ $# == 0 ]; then
            chmod -R 777 *
            find dev-sdk/src/main/java/ -name "*.java" -exec java -jar ./google-java-format-1.12.0-all-deps.jar -i -r -a --skip-reflowing-long-strings --skip-javadoc-formatting {} \;
            echo "------------------------------------git status------------------------------------"
            git status>>format.txt
            git add .
            git config --global user.name "qq"
            git config --global user.email "qingquan.c@analysys.com.cn"
            git commit -am "WIP: test upload"
            git push
          fi # end with down load process
      - name: Upload google-java-format result
        uses: actions/upload-artifact@v1
        continue-on-error: true
        with:
          name: google-java-format.txt
          path: ./format.txt
