name: Android CI


on:
  push:
    branches: [ main ]

jobs:
  build:

    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    if: ${{ !startsWith(github.event.head_commit.message, 'WID') }}
    #if: "! contains(github.event.head_commit.message, 'gitaction')"
    #if: "contains(github.event.head_commit.message, '[build]')"
    

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: Gradle build
      shell: bash
      continue-on-error: true
      run: |
        chmod -R 777 *
        git config core.filemode false
        ./gradlew build
