name: Android CI


on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, 'WIP')"

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: Gradle build
      shell: bash
      #continue-on-error: true
      run: |
        chmod -R 777 *
        git config core.filemode false
        ./gradlew build
        echo "==========================查看目录==============="
        ls
        echo "=======================开始安装软件======================="
        sudo apt-get update
        sudo apt-get -y install net-tools apt-transport-https ca-certificates curl software-properties-common
        curl -fsSL https://mirrors.aliyun.com/docker-ce/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://mirrors.aliyun.com/docker-ce/linux/ubuntu $(lsb_release -cs) stable"
        sudo apt-get -y update
        #sudo add-apt-repository  "deb [arch=amd64] https://mirrors.ustc.edu.cn/docker-ce/linux/ubuntu/ $(lsb_release -cs) stable"
        #sudo apt-get -y update
        sudo apt-get -y install docker-ce
        sudo apt install cpu-checker
        
        # #使用 apt-get 进行安装
        # # step 1: 安装必要的一些系统工具
        # sudo apt-get update
        # sudo apt-get -y install apt-transport-https ca-certificates curl software-properties-common
        # # step 2: 安装GPG证书
        # curl -fsSL https://mirrors.aliyun.com/docker-ce/linux/ubuntu/gpg | sudo apt-key add -
        # # Step 3: 写入软件源信息
        # sudo add-apt-repository "deb [arch=amd64] https://mirrors.aliyun.com/docker-ce/linux/ubuntu $(lsb_release -cs) stable"
        # # Step 4: 更新并安装Docker-CE
        # sudo apt-get -y update
        # sudo apt-get -y install docker-ce
        ## 安装指定版本的Docker-CE:
        ## Step 1: 查找Docker-CE的版本:
        ## apt-cache madison docker-ce
        ##   docker-ce | 17.03.1~ce-0~ubuntu-xenial | https://mirrors.aliyun.com/docker-ce/linux/ubuntu xenial/stable amd64 Packages
        ##   docker-ce | 17.03.0~ce-0~ubuntu-xenial | https://mirrors.aliyun.com/docker-ce/linux/ubuntu xenial/stable amd64 Packages
        ## Step 2: 安装指定版本的Docker-CE: (VERSION例如上面的17.03.1~ce-0~ubuntu-xenial)
        ## sudo apt-get -y install docker-ce=[VERSION]
        echo "=======================安装完毕，uname测试======================="
        uname -a
        kvm-ok
        # echo "================================================即将测试命令 docker:========================"
        # docker
        echo "================================================即将测试 docker hello-world========================"
        sudo docker run hello-world
        echo "================================================即将测试IP地址========================"
        ip=`ifconfig -a|grep inet|grep -v 127.0.0.1|grep -v inet6|awk '{print $2}'|tr -d "addr:"`
        echo "方式一获取ip： $ip"
        ip2=$(ifconfig -a|grep inet|grep -v 127.0.0.1|grep -v inet6|awk '{print $2}'|tr -d "addr:")
        echo "方式二获取ip： $ip2"
        ### export PATH
        export PATH=$PATH:${ANDROID_HOME}/emulator:${ANDROID_HOME}/platform-tools:${ANDROID_HOME}/tools:${ANDROID_HOME}/tools/bin:${ANDROID_HOME}/build-tools/30.0.3:${ANDROID_HOME}/build-tools/30.0.3/lld-bin:${ANDROID_HOME}/ndk/23.0.7599858
        echo "=========测试命令adb==========="
        adb devices
        echo "=================================即将安装docker==================================="
        docker run --privileged -d -p 6080:6080 -p 5554:5554 -p 5555:5555 -e DEVICE="Samsung Galaxy S6" --name android-container budtmo/docker-android-x86-8.1
        echo "=================================安装docker完毕，adb查看设备==================================="
        adb devices





