name: Android CI


on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, 'WIP')"

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: Gradle build
      shell: bash
      continue-on-error: true
      run: |
        chmod -R 777 *
        git config core.filemode false
        ./gradlew build
        echo "==========================查看目录==============="
        ls
        echo "=======================开始安装软件======================="
        sudo apt-get install apt-transport-https ca-certificates curl gnupg lsb-release net-tools
        echo "=======================update======================="
        sudo apt-get update
        echo "=======================UNAME======================="
        uname -a
        echo "=======================install dcoker======================="
        sudo apt-get install docker
        echo "=======================import gpg======================="
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        echo "====================================安装软件完毕========================"
        echo "================================================即将测试命令 docker:========================"
        docker
        ip=`ifconfig -a|grep inet|grep -v 127.0.0.1|grep -v inet6|awk '{print $2}'|tr -d "addr:"`
        echo "方式一获取ip： $ip"
        ip2=$(ifconfig -a|grep inet|grep -v 127.0.0.1|grep -v inet6|awk '{print $2}'|tr -d "addr:")
        echo "方式二获取ip： $ip2"
        ### export PATH
        export PATH=$PATH:${ANDROID_HOME}/emulator:${ANDROID_HOME}/platform-tools:${ANDROID_HOME}/tools:${ANDROID_HOME}/tools/bin:${ANDROID_HOME}/build-tools/30.0.3:${ANDROID_HOME}/build-tools/30.0.3/lld-bin:${ANDROID_HOME}/ndk/23.0.7599858
        echo "=========测试命令adb==========="
        adb
        echo "=========测试命令fastboot==========="
        fastboot




